# Generated by Django 4.0.1 on 2022-07-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(upload_to='competitionImage', verbose_name='封面圖'),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(upload_to='membersImage', verbose_name='照片'),
        ),
    ]
