# Generated by Django 4.0.1 on 2022-07-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_events_members_thumb_alter_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.CharField(choices=[('1', '大砲'), ('2', '舉球'), ('3', '自由'), ('4', '副攻'), ('5', '欄中'), ('6', '輔舉'), ('7', '耍寶')], max_length=1, verbose_name='位置'),
        ),
    ]
